// Base de datos de apellidos para parsing de Cédula Digital
// Se incluyen apellidos comunes, regionales, indígenas y extranjeros comunes en Colombia.

const LISTA_BASE = [
  // --- A ---
  'ABAD', 'ABADIA', 'ABELLO', 'ABRIL', 'ABREO', 'ACEVEDO', 'ACERO', 'ACHICUE', 'ACOSTA', 'ACUÑA', 
  'ADAMES', 'ADARME', 'AFANADOR', 'AGREDO', 'AGUALIMPIA', 'AGUDELO', 'AGUILAR', 'AGUILERA', 
  'AGUIRRE', 'ALARCON', 'ALBAN', 'ALBARRACIN', 'ALBERNIA', 'ALCALA', 'ALCANTARA', 'ALDANA', 
  'ALEGRIA', 'ALFONSO', 'ALI', 'ALMANZA', 'ALMARIO', 'ALMEIDA', 'ALONSO', 'ALTAMAR', 'ALTAMIRANO',
  'ALVARADO', 'ALVAREZ', 'ALVEAR', 'ALVIRA', 'ALZATE', 'AMADO', 'AMADOR', 'AMAYA', 'AMAZO', 
  'AMBROSIO', 'AMEZQUITA', 'AMORTEGUI', 'AMPUDIA', 'ANACONA', 'ANAYA', 'ANCHICO', 'ANDRADE', 
  'ANGARITA', 'ANGEL', 'ANGULO', 'ANSERA', 'ANTELIZ', 'ANTURI', 'ANZOLA', 'APARICIO', 'APONTE', 
  'AQUINO', 'ARAGON', 'ARANA', 'ARANGO', 'ARANZAZU', 'ARAUJO', 'ARBELAEZ', 'ARBOLEDA', 'ARCE', 
  'ARCILA', 'ARCINIEGAS', 'ARDILA', 'ARENAS', 'AREVALO', 'ARGUELLO', 'ARIAS', 'ARIZA', 'ARJONA', 
  'ARMERO', 'ARMENTA', 'ARREGOCES', 'ARRIETA', 'ARROYO', 'ARTUNDUAGA', 'ARTEAGA', 'ASPRILLA', 
  'ASTAIZA', 'ASTUDILLO', 'ATEHORTUA', 'ATENCIA', 'ATENCIO', 'ATUESTA', 'AVALOS', 'AVENDAÑO', 
  'AVILA', 'AVILES', 'AYALA', 'AYOLA', 'AZCARATE', 

  // --- B ---
  'BACA', 'BACHILLER', 'BADILLO', 'BAENA', 'BAEZ', 'BAEZA', 'BAHAMON', 'BAHAMONDE', 'BALANTA', 
  'BALAGUERA', 'BALBIN', 'BALCAZAR', 'BALDOVINO', 'BALLEN', 'BALLESTEROS', 'BALLESTAS', 'BANDA', 
  'BANDERA', 'BANGUERA', 'BANGUERO', 'BAQUERO', 'BARACALDO', 'BARAHONA', 'BARAJAS', 'BARBOSA', 
  'BARCO', 'BARON', 'BARRAGAN', 'BARRAZA', 'BARRERA', 'BARRETO', 'BARRIENTOS', 'BARRIOS', 'BARROS', 
  'BARTOLO', 'BASTIDAS', 'BASTO', 'BATISTA', 'BAUTISTA', 'BAYONA', 'BAZURTO', 'BECERRA', 'BEDOYA', 
  'BEJARANO', 'BELALCAZAR', 'BELTRAN', 'BELLO', 'BELLON', 'BENAVIES', 'BENAVIDES', 'BENITEZ', 
  'BENJUMEA', 'BERDUGO', 'BERMUDEZ', 'BERNAL', 'BERNATE', 'BERRIO', 'BERTEL', 'BETANCUR', 
  'BETANCOURT', 'BETIN', 'BLANCO', 'BLANDON', 'BOCANEGRA', 'BOHORQUEZ', 'BOLAÑOS', 'BOLIVAR', 
  'BONILLA', 'BORDA', 'BORGE', 'BORJA', 'BORRERO', 'BOSSA', 'BOTERO', 'BOTINA', 'BRAVO', 'BRICEÑO', 
  'BRITO', 'BUELVAS', 'BUENAHORA', 'BUENDIA', 'BUENO', 'BUITRAGO', 'BURBANO', 'BURGOS', 'BUSTAMANTE', 
  'BUSTOS', 

  // --- C ---
  'CABALLERO', 'CABAL', 'CABARCAS', 'CABEZAS', 'CABRA', 'CABRALES', 'CABRERA', 'CACERES', 
  'CADAVID', 'CADENA', 'CAICEDO', 'CAJAMARCA', 'CAJIAO', 'CALA', 'CALAMBAS', 'CALDAS', 'CALDERON', 
  'CALERO', 'CALLE', 'CALLEJAS', 'CALVO', 'CAMACHO', 'CAMARGO', 'CAMELO', 'CAMARILLO', 'CAMPO', 
  'CAMPOS', 'CANACUE', 'CANALES', 'CANDANOZA', 'CANDELA', 'CANDELO', 'CANIZALES', 'CANO', 'CANON', 
  'CANTILLO', 'CAÑAS', 'CAÑON', 'CAÑIZARES', 'CAPACHO', 'CAPERA', 'CARABALI', 'CARABALLO', 
  'CARVAJAL', 'CARVAJALINO', 'CARDENAS', 'CARDONA', 'CARDOZO', 'CARMONA', 'CARO', 'CARRANZA', 
  'CARRASCAL', 'CARRASCO', 'CARRASQUILLA', 'CARREÑO', 'CARRILLO', 'CARRILLO', 'CARRIZOSA', 
  'CARTAGENA', 'CARVAJAL', 'CASALLAS', 'CASANOVA', 'CASAS', 'CASERES', 'CASIANI', 'CASTAÑEDA', 
  'CASTAÑO', 'CASTELLANOS', 'CASTELLAR', 'CASTILLO', 'CASTRILLON', 'CASTRO', 'CATANO', 'CAUSIL', 
  'CAVALIER', 'CAVIEDES', 'CAYCEDO', 'CAYON', 'CEBALLOS', 'CEDEÑO', 'CELEDON', 'CELIS', 'CELIS', 
  'CEPERO', 'CEPEDA', 'CERON', 'CERQUERA', 'CERVANTES', 'CESPEDES', 'CETINA', 'CHACON', 'CHALA', 
  'CHAMORRO', 'CHAPARRO', 'CHAR', 'CHARRIS', 'CHAVARRIA', 'CHAVEZ', 'CHAVERRA', 'CHICA', 'CHICUE', 
  'CHINCHILLA', 'CHINDICUE', 'CHIVATA', 'CIFUENTES', 'CIPAGUAUTA', 'CISNEROS', 'CLAROS', 'CLAVIJO', 
  'COBO', 'COBOS', 'COGOLLO', 'COHEN', 'COLLAZOS', 'COLMENARES', 'COLON', 'COLORADO', 'CONDE', 
  'CONEJO', 'CONTRERAS', 'COPETE', 'CORBA', 'CORCHUELO', 'CORDERO', 'CORDOBA', 'CORONADO', 
  'CORONEL', 'CORRAL', 'CORRALES', 'CORREA', 'CORREAL', 'CORREDOR', 'CORTES', 'CORTINA', 'CORZO', 
  'COSSIO', 'COSTA', 'COTES', 'COTRINA', 'CRIOLLO', 'CRUZ', 'CUADRADO', 'CUADROS', 'CUAICAL', 
  'CUARTAS', 'CUBIDES', 'CUBILLOS', 'CUCHUMBA', 'CUELLAR', 'CUENCA', 'CUERVO', 'CUEVAS', 'CUJIA', 
  'CULMA', 'CUMBA', 'CURREA', 'CURVELO', 

  // --- D ---
  'DAZA', 'DANGOND', 'DANIEL', 'DAVILA', 'DE AVILA', 'DE LA CRUZ', 'DE LA HOZ', 'DE LA OSSA', 
  'DE LA PAVA', 'DE LA ROSA', 'DE LA TORRE', 'DE LEON', 'DE LUQUE', 'DEL CASTILLO', 'DEL RIO', 
  'DEL VALLE', 'DELGADO', 'DEVIA', 'DIAZ', 'DIAZGRANADOS', 'DIAGO', 'DOMINGUEZ', 'DONADO', 
  'DORADO', 'DUARTE', 'DUEÑAS', 'DUQUE', 'DURAN', 'DURANGO', 'DUSSAN', 

  // --- E ---
  'ECHAVARRIA', 'ECHEVERRI', 'ECHEVERRY', 'EGAS', 'ELEJALDE', 'ELIAS', 'ELJURE', 'ENCISO', 
  'ENRIQUEZ', 'EPIAYU', 'ERAZO', 'ESCALANTE', 'ESCAMILLA', 'ESCARRAGA', 'ESCOBAR', 'ESCORCIA', 
  'ESCUDERO', 'ESGUERRA', 'ESPAÑA', 'ESPEJO', 'ESPINAL', 'ESPINEL', 'ESPITIA', 'ESPINOSA', 
  'ESPINOZA', 'ESQUIVEL', 'ESTEVEZ', 'ESTRADA', 'ESTUPIÑAN', 

  // --- F ---
  'FABRA', 'FACUNDO', 'FAJARDO', 'FALLA', 'FANDIÑO', 'FONSECA', 'FARFAN', 'FAURA', 'FERIA', 
  'FERNANDEZ', 'FERRER', 'FERRO', 'FIGUEROA', 'FIGUEREDO', 'FIERRO', 'FLOREZ', 'FLORES', 'FONTALVO', 
  'FONSECA', 'FORERO', 'FORERO', 'FORTICH', 'FRAGOSO', 'FRAILE', 'FRANCO', 'FREYLE', 'FUENTES', 
  'FULA', 'FUNEZ', 'FURLONG', 

  // --- G ---
  'GAITAN', 'GALAN', 'GALARZA', 'GALINDO', 'GALLEGO', 'GALLO', 'GALVIS', 'GAMARRA', 'GAMBOA', 
  'GAMEZ', 'GARAVITO', 'GARCES', 'GARCIA', 'GARIZAO', 'GARRIDO', 'GARZON', 'GASCA', 'GAVIRIA', 
  'GELVEZ', 'GENEY', 'GERENA', 'GIL', 'GIRALDO', 'GIRON', 'GODOY', 'GOENAGA', 'GOMEZ', 'GONGORA', 
  'GONZALEZ', 'GORDILLO', 'GOYES', 'GRACIA', 'GRANADOS', 'GRANDA', 'GRANOBLES', 'GRAJALES', 
  'GRECCO', 'GRIJALBA', 'GRISALES', 'GROSSO', 'GUACA', 'GUALDRON', 'GUALTEROS', 'GUANUME', 
  'GUAPACHA', 'GUARACA', 'GUARIN', 'GUARNIZO', 'GUASCA', 'GUATIBONZA', 'GUAUNA', 'GUERRA', 
  'GUERRERO', 'GUEVARA', 'GUILLEN', 'GUIO', 'GUISAO', 'GUTIERREZ', 'GUZMAN', 

  // --- H ---
  'HENAO', 'HENRIQUEZ', 'HEREDIA', 'HERAZO', 'HERMOSA', 'HERNANDEZ', 'HERRERA', 'HERREÑO', 
  'HEVIA', 'HIGUERA', 'HIGUITA', 'HINCAPIE', 'HINESTROZA', 'HOLGUIN', 'HORTA', 'HOYOS', 'HUERTAS', 
  'HUERFANO', 'HURTADO', 

  // --- I ---
  'IBAÑEZ', 'IBARRA', 'IBARGÜEN', 'IGLESIAS', 'IGUA', 'ILLERA', 'INFANTE', 'IPUANA', 'IRIARTE', 
  'ISAS', 'ISAZA', 'IZQUIERDO', 

  // --- J ---
  'JACANAMEJOY', 'JACOME', 'JAIMES', 'JALLER', 'JAMES', 'JARAMILLO', 'JARABA', 'JAUREGUI', 'JEREZ', 
  'JIMENEZ', 'JOAQUI', 'JORDAN', 'JOYA', 'JULIO', 'JUNCO', 'JURADO', 'JUSAYU', 

  // --- K ---
  'KALIL', 'KAFURY', 'KERGUELEN', 'KUMAR', 

  // --- L ---
  'LABRADOR', 'LACOUTURE', 'LADINO', 'LAFAURIE', 'LAGOS', 'LAGUNA', 'LAHOZ', 'LAMILLA', 'LAMUS', 
  'LANDAZABAL', 'LANDAZURI', 'LANCHEROS', 'LARA', 'LARGO', 'LARRAHONDO', 'LARROTA', 'LASSO', 
  'LASTRA', 'LAVERDE', 'LAZARO', 'LEAL', 'LEGUIZAMON', 'LEIVA', 'LEMUS', 'LEON', 'LERMA', 
  'LEZCANO', 'LIBERATO', 'LIEVANO', 'LIGARRETO', 'LIMA', 'LINARES', 'LINERO', 'LIZARAZO', 
  'LIZCANO', 'LLANOS', 'LLERAS', 'LLERENA', 'LLOREDA', 'LOAIZA', 'LOBATON', 'LOBOGUERRERO', 
  'LOBO', 'LOMBANA', 'LONDONO', 'LONDOÑO', 'LOPERA', 'LOPEZ', 'LORA', 'LOZADA', 'LOZANO', 'LUCIO', 
  'LUGARI', 'LUGO', 'LUENGAS', 'LUQUE', 'LUNA', 

  // --- M ---
  'MAAL', 'MACEA', 'MACHADO', 'MACIAS', 'MADERO', 'MADRID', 'MADRIGAL', 'MAESTRE', 'MAGDIEL', 
  'MAHECHA', 'MALAGON', 'MALAVER', 'MALDONADO', 'MALLAMA', 'MAMIAN', 'MANCERA', 'MANCIPE', 
  'MANCO', 'MANGA', 'MANGONES', 'MANJARRES', 'MANRIQUE', 'MANTILLA', 'MANZANO', 'MAQUILON', 
  'MARIN', 'MARIÑO', 'MARMOLEJO', 'MARQUEZ', 'MARROQUIN', 'MARRUGO', 'MARTEL', 'MARTELO', 
  'MARTIN', 'MARTINEZ', 'MARULANDA', 'MASMELA', 'MATALLANA', 'MATIZ', 'MATOS', 'MATTA', 'MAYA', 
  'MAYORGA', 'MAZA', 'MAZO', 'MAZUERA', 'MEDINA', 'MEDRANO', 'MEJIA', 'MELENDEZ', 'MELGAREJO', 
  'MELO', 'MENA', 'MENDEZ', 'MENDOZA', 'MENESES', 'MERCADO', 'MERCHAN', 'MERIÑO', 'MESA', 
  'MESTRA', 'MEZA', 'MEZQUITA', 'MIER', 'MIERES', 'MIGUEL', 'MILLAN', 'MINA', 'MINOTA', 'MIRA', 
  'MIRANDA', 'MOGOLLON', 'MOJICA', 'MOLANO', 'MOLINA', 'MOLINARES', 'MONCADA', 'MONDRAGON', 
  'MONROY', 'MONSALVE', 'MONTAÑA', 'MONTAÑO', 'MONTALVO', 'MONTANEZ', 'MONTEALEGRE', 'MONTEALIEGRE',
  'MONTENEGRO', 'MONTERO', 'MONTERROSA', 'MONTES', 'MONTEZUMA', 'MONTIEL', 'MONTOYA', 'MONZON', 
  'MORA', 'MORALES', 'MORELO', 'MORENO', 'MORANTES', 'MORATO', 'MOSCOSO', 'MOSQUERA', 'MOTA', 
  'MOTTA', 'MOTOA', 'MOYA', 'MUESES', 'MULFORD', 'MUNAR', 'MUNEVAR', 'MUÑOZ', 'MUÑETONES', 
  'MURCIA', 'MURIEL', 'MURILLO', 'MUSKUS', 'MUTIS', 

  // --- N ---
  'NADER', 'NAJAR', 'NARANJO', 'NARVAEZ', 'NAVAS', 'NAVARRETE', 'NAVARRO', 'NAVIA', 'NEGRON', 
  'NEIRA', 'NEME', 'NEUTA', 'NIETO', 'NIEVES', 'NIÑO', 'NOGUERA', 'NOPE', 'NORIEGA', 'NOREÑA', 
  'NOVOA', 'NUCAMENDI', 'NUÑEZ', 

  // --- O ---
  'OBANDO', 'OBESO', 'OBREGON', 'OCAMPO', 'OCAÑA', 'OCHOA', 'OCORO', 'OJEDA', 'OLANO', 'OLARTE', 
  'OLAYA', 'OLIVA', 'OLIVARES', 'OLIVELLA', 'OLIVERA', 'OLIVEROS', 'OLIVO', 'OLMOS', 'OÑATE', 
  'ORDUZ', 'ORDOÑEZ', 'OREJUELA', 'ORJUELA', 'OROZCO', 'ORTEGA', 'ORTEGON', 'ORTIZ', 'OSORIO', 
  'OSPINA', 'OSPINO', 'OSSA', 'OSSES', 'OSUNA', 'OTALORA', 'OTALVARO', 'OTERO', 'OTAROLA', 
  'OVALLE', 'OVIEDO', 'OYOLA', 

  // --- P ---
  'PABON', 'PACHECO', 'PACHON', 'PADILLA', 'PAEZ', 'PAJARO', 'PALACIO', 'PALACIOS', 'PALENCIA', 
  'PALLARES', 'PALMA', 'PALOMINO', 'PANTOJA', 'PARADA', 'PARDO', 'PAREDES', 'PAREJA', 'PARRA', 
  'PARRADO', 'PASCUAS', 'PASOS', 'PASTRANA', 'PATARROYO', 'PATERNINA', 'PATIÑO', 'PAVA', 'PAVAS', 
  'PAYAN', 'PAZ', 'PEDRAZA', 'PEDREROS', 'PEDROZA', 'PEINADO', 'PELAEZ', 'PELAYO', 'PENAGOS', 
  'PEÑA', 'PEÑALOZA', 'PEÑARANDA', 'PEÑATE', 'PERAFAN', 'PERALTA', 'PERDOMO', 'PEREA', 'PEREIRA', 
  'PEREZ', 'PERILLA', 'PERLAZA', 'PERTUZ', 'PETRO', 'PEZUELA', 'PICO', 'PICON', 'PIEDRAHITA', 
  'PIMIENTA', 'PINEDA', 'PINILLA', 'PINILLOS', 'PINO', 'PINTOR', 'PINTO', 'PINZON', 'PIÑERES', 
  'PIZARRO', 'PLATA', 'PLAZAS', 'POLANCO', 'POLANIA', 'POLO', 'POMBO', 'PONARE', 'PONCE', 'PONNEFLEZ',
  'PORRAS', 'PORTELA', 'PORTILLA', 'PORTILLO', 'POSADA', 'POSSO', 'POTES', 'POVEDA', 'POZO', 
  'PRADA', 'PRADO', 'PRATO', 'PRECIADO', 'PRETEL', 'PRIETO', 'PRADA', 'PUERTA', 'PUENTES', 
  'PUERTO', 'PUGA', 'PUIDO', 'PUJOL', 'PULECHIO', 'PULGARIN', 'PULIDO', 'PUMAREJO', 'PUPO', 
  'PUSHAINA', 'PUYANA', 

  // --- Q ---
  'QUEJADA', 'QUEVEDO', 'QUIBANO', 'QUICENO', 'QUIJANO', 'QUINCHE', 'QUINTERO', 'QUIÑONES', 
  'QUIÑONEZ', 'QUIROGA', 'QUIROZ', 'QUITIAN', 

  // --- R ---
  'RADA', 'RAIGOSA', 'RAIGOZA', 'RAMIREZ', 'RAMOS', 'RANGEL', 'RAPALINO', 'RAVE', 'REALES', 
  'REALPE', 'REATIGA', 'REBOLLEDO', 'REDONDO', 'REGALADO', 'REINA', 'REINOSO', 'RENGIFO', 
  'RENTERIA', 'RESTREPO', 'REVUELTAS', 'REY', 'REYES', 'REYNEL', 'REYNOSO', 'RHEIN', 'RIAÑO', 
  'RIASCOS', 'RICAURTE', 'RICO', 'RINCON', 'RIOS', 'RIVADENEIRA', 'RIVAS', 'RIVERA', 'RIVERO', 
  'ROA', 'ROBAYO', 'ROBLEDO', 'ROBLES', 'ROCA', 'ROCHA', 'RODADILLO', 'RODAS', 'RODRIGUEZ', 
  'ROJAS', 'ROJO', 'ROLDAN', 'ROMAN', 'ROMERO', 'ROMO', 'RONCANCIO', 'RONDON', 'ROSADO', 'ROSALES', 
  'ROSAS', 'ROSERO', 'ROZO', 'RUA', 'RUBIANO', 'RUBIO', 'RUEDA', 'RUESGA', 'RUGELES', 'RUIZ', 

  // --- S ---
  'SAAVEDRA', 'SABOGAL', 'SACHICA', 'SAENZ', 'SAGRE', 'SAHAGUN', 'SAIZ', 'SALAMANCA', 'SALAS', 
  'SALAZAR', 'SALCEDO', 'SALDAÑA', 'SALDARRIAGA', 'SALGADO', 'SALINAS', 'SAMPER', 'SAMUDIO', 
  'SANABRIA', 'SANCHEZ', 'SANDOVAL', 'SANIN', 'SANJUAN', 'SANMIGUEL', 'SANTA', 'SANTACRUZ', 
  'SANTAMARIA', 'SANTANA', 'SANTANDER', 'SANTIAGO', 'SANTOS', 'SANTOYO', 'SANZ', 'SARABIA', 
  'SARASTI', 'SARMIENTO', 'SARRIA', 'SASTOQUE', 'SAUCEDO', 'SCHAMUN', 'SCHOONEWOLFF', 'SEGOVIA', 
  'SEGURA', 'SEMANATE', 'SEPULVEDA', 'SERNA', 'SERPA', 'SERRANO', 'SIERRA', 'SILVA', 'SILVERA', 
  'SIMANCA', 'SIMIJACA', 'SINISTERRA', 'SOCHA', 'SOLANO', 'SOLARTE', 'SOLER', 'SOLIS', 'SOLORZANO', 
  'SOMOZA', 'SORACA', 'SORIA', 'SOSA', 'SOTO', 'SOUSE', 'SUAREZ', 'SUAZA', 'SUESCUN', 'SURMAY', 

  // --- T ---
  'TABA', 'TABARES', 'TABOADA', 'TABORDA', 'TAFUR', 'TAMAYO', 'TAMARA', 'TANGARIFE', 'TANUS', 
  'TAPIA', 'TAPIAS', 'TAPICERO', 'TAPIERO', 'TARAZONA', 'TASCÓN', 'TATA', 'TATIS', 'TEJADA', 
  'TELLEZ', 'TELLO', 'TENORIO', 'TERAN', 'TESILLO', 'TIBAQUIRA', 'TIBOCHA', 'TIGREROS', 'TINJACA', 
  'TIRADO', 'TISNES', 'TOBAR', 'TOBON', 'TOLEDO', 'TOLOZA', 'TORO', 'TORRADO', 'TORRALVO', 
  'TORREGROSA', 'TORRES', 'TORRIJOS', 'TOSCANO', 'TOVAR', 'TREJOS', 'TRIANA', 'TRIVIÑO', 
  'TROCHEZ', 'TRUJILLO', 'TUTALCHA', 'TUIRAN', 

  // --- U ---
  'UBATE', 'UCRIS', 'UEJA', 'ULCHUR', 'ULLOA', 'UMAÑA', 'UMBARILA', 'URBANO', 'URBINA', 
  'URDANETA', 'UREÑA', 'URIANA', 'URIBE', 'URIGO', 'URIZA', 'URREA', 'URREGO', 'USMA', 'USME', 
  'USUGA', 

  // --- V ---
  'VACA', 'VALBUENA', 'VALDERRAMA', 'VALDES', 'VALDEZ', 'VALDIVIESO', 'VALENCIA', 'VALENZUELA', 
  'VALERO', 'VALLE', 'VALLEJO', 'VANALEN', 'VANEGAS', 'VAQUIRO', 'VARA', 'VARELA', 'VARGAS', 
  'VARON', 'VASQUEZ', 'VEGA', 'VELA', 'VELANDIA', 'VELASCO', 'VELASQUEZ', 'VELEZ', 'VELIZ', 
  'VELOSA', 'VENDRIES', 'VENEGAS', 'VENTE', 'VERA', 'VERBEL', 'VERDUGO', 'VERGARA', 'VERGEL', 
  'VIANA', 'VIAZUS', 'VICTORIA', 'VIDAL', 'VIEDA', 'VIKTOR', 'VILLA', 'VILLABONA', 'VILLADA', 
  'VILLADIEGO', 'VILLALBA', 'VILLALOBOS', 'VILLAMARIN', 'VILLAMIL', 'VILLAMIZAR', 'VILLANUEVA', 
  'VILLAREAL', 'VILLARRAGA', 'VILLARREAL', 'VILLAZON', 'VILLEGAS', 'VILLOTA', 'VINASCO', 'VINAZCO', 
  'VIRGUEZ', 'VISBAL', 'VITOLA', 'VIVAS', 'VIVEROS', 'VIZCAINO', 

  // --- W - Y - Z ---
  'WADE', 'WALLS', 'WALTEROS', 'WIESNER', 'WILLIAMS', 'WILCHES', 'WOLFF', 
  'YANCES', 'YANEZ', 'YATE', 'YEPES', 'YEPEZ', 'YERENA', 'YUNDA', 'YUSTRES', 
  'ZABALA', 'ZABALETA', 'ZAMBRANO', 'ZAMORA', 'ZAMUDIO', 'ZAPATA', 'ZARATE', 'ZARAZA', 'ZARUR', 
  'ZEA', 'ZULETA', 'ZULUAGA', 'ZUÑIGA'
];

// EXPORTACIÓN ORDENADA:
// Ordenamos la lista por longitud descendente (los apellidos más largos primero).
// ESTO ES CRÍTICO: Evita que "SANTAMARIA" se corte erróneamente como "SANTA".
export const APELLIDOS_COLOMBIANOS = LISTA_BASE.sort((a, b) => b.length - a.length);